import React, { useEffect, useRef, useState, useCallback, useMemo } from 'react';
import {
  Play,
  Pause,
  Download,
  Film,
  Sparkles,
  RotateCcw,
  Plus,
  Trash2,
  Upload,
  Check,
  Crosshair,
  Sliders,
  Palette,
  Code2,
  Copy,
  ExternalLink,
  FileCode,
  Layers,
  Eye,
} from 'lucide-react';
import {
  CONSTELLATION_PRESETS,
  DEFAULT_STUDIO_CONFIG,
  ExportRecord,
  GRADIENT_PRESETS,
  GradientWaveMode,
  HtmlExportMode,
  LogoStudioConfig,
  RESOLUTION_PRESETS,
  StarNode,
} from './types/logoStudio';
import { renderLogoFrame } from './utils/canvasRenderer';
import { encodeAnimatedGif } from './utils/gifEncoder';
import { recordCanvasVideo } from './utils/videoExporter';
import { generateSvgCssHtml, generateCanvasJsHtml } from './utils/htmlCodeGenerator';

type ControlTab = 'gradient' | 'stars' | 'typography' | 'html-code' | 'exports';

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  const kb = bytes / 1024;
  if (kb < 1024) return `${kb.toFixed(1)} KB`;
  return `${(kb / 1024).toFixed(2)} MB`;
}

export default function App() {
  const [config, setConfig] = useState<LogoStudioConfig>(DEFAULT_STUDIO_CONFIG);
  const [activeTab, setActiveTab] = useState<ControlTab>('html-code');
  const [isPlaying, setIsPlaying] = useState<boolean>(true);
  const [loopProgress, setLoopProgress] = useState<number>(0);
  const [interactiveEditStars, setInteractiveEditStars] = useState<boolean>(false);
  const [selectedStarId, setSelectedStarId] = useState<string | null>('s7');
  const [draggingStarId, setDraggingStarId] = useState<string | null>(null);

  // Custom uploaded image reference for hybrid mode
  const [customImage, setCustomImage] = useState<HTMLImageElement | null>(null);
  const [customImageName, setCustomImageName] = useState<string>('');

  // HTML Code states
  const [htmlMode, setHtmlMode] = useState<HtmlExportMode>('svg-css');
  const [copySuccess, setCopySuccess] = useState<boolean>(false);
  const [showLiveHtmlPreview, setShowLiveHtmlPreview] = useState<boolean>(false);

  // Export states
  const [isEncodingGif, setIsEncodingGif] = useState<boolean>(false);
  const [isRecordingVideo, setIsRecordingVideo] = useState<boolean>(false);
  const [exportProgress, setExportProgress] = useState<number>(0);
  const [exportStatusText, setExportStatusText] = useState<string>('');
  const [exportsList, setExportsList] = useState<ExportRecord[]>([]);

  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const progressRef = useRef<number>(0);
  const lastFrameTimeRef = useRef<number | null>(null);
  const autoGeneratedInitialGifRef = useRef<boolean>(false);

  const activeResolution =
    RESOLUTION_PRESETS.find((r) => r.id === config.resolutionId) || RESOLUTION_PRESETS[0];

  const totalFrames = Math.round(config.fps * config.loopDurationSec);
  const currentFrameNumber = Math.min(
    totalFrames,
    Math.floor(loopProgress * totalFrames) + 1
  );

  const updateConfig = useCallback((patch: Partial<LogoStudioConfig>) => {
    setConfig((prev) => ({ ...prev, ...patch }));
  }, []);

  // Generate current standalone HTML code based on active settings
  const generatedHtmlCode = useMemo(() => {
    if (htmlMode === 'svg-css') {
      return generateSvgCssHtml(config, activeResolution.width, activeResolution.height);
    }
    return generateCanvasJsHtml(config, activeResolution.width, activeResolution.height);
  }, [config, htmlMode, activeResolution.width, activeResolution.height]);

  // Main real-time 60fps animation loop
  useEffect(() => {
    let rafId: number;

    const animate = (timestamp: number) => {
      if (lastFrameTimeRef.current === null) {
        lastFrameTimeRef.current = timestamp;
      }
      const dtSec = (timestamp - lastFrameTimeRef.current) / 1000;
      lastFrameTimeRef.current = timestamp;

      if (isPlaying && !draggingStarId) {
        progressRef.current =
          (progressRef.current + dtSec / config.loopDurationSec) % 1;
        setLoopProgress(progressRef.current);
      }

      const canvas = canvasRef.current;
      if (canvas) {
        const ctx = canvas.getContext('2d');
        if (ctx) {
          renderLogoFrame(
            ctx,
            activeResolution.width,
            activeResolution.height,
            progressRef.current,
            config,
            customImage,
            interactiveEditStars ? selectedStarId : null
          );
        }
      }

      rafId = requestAnimationFrame(animate);
    };

    rafId = requestAnimationFrame(animate);
    return () => cancelAnimationFrame(rafId);
  }, [
    isPlaying,
    config,
    activeResolution.width,
    activeResolution.height,
    customImage,
    interactiveEditStars,
    selectedStarId,
    draggingStarId,
  ]);

  // Download standalone HTML file (.html)
  const handleDownloadHtmlFile = useCallback(() => {
    const code = generatedHtmlCode;
    const blob = new Blob([code], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const slug = (config.titleText || 'logo')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-');
    const filename = `${slug}-animated-${htmlMode}.html`;

    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);

    const newRecord: ExportRecord = {
      id: `html-${Date.now()}`,
      format: 'HTML',
      url,
      filename,
      width: activeResolution.width,
      height: activeResolution.height,
      fps: 60,
      durationSec: config.loopDurationSec,
      sizeBytes: blob.size,
      createdAt: new Date().toLocaleTimeString('id-ID', {
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
      }),
    };
    setExportsList((prev) => [newRecord, ...prev]);
  }, [generatedHtmlCode, config.titleText, htmlMode, activeResolution, config.loopDurationSec]);

  // Copy HTML code to clipboard
  const handleCopyHtmlCode = useCallback(() => {
    navigator.clipboard.writeText(generatedHtmlCode).then(() => {
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2400);
    });
  }, [generatedHtmlCode]);

  // Trigger GIF generation and download
  const handleGenerateGif = useCallback(
    async (autoDownload = true) => {
      if (isEncodingGif || isRecordingVideo) return;
      setIsEncodingGif(true);
      setExportProgress(0);
      setExportStatusText('Merender frame & palet warna adaptif GIF89a...');

      try {
        if (document.fonts && document.fonts.ready) {
          await document.fonts.ready;
        }

        const framesCount = Math.round(config.fps * config.loopDurationSec);
        const gifBlob = await encodeAnimatedGif({
          width: activeResolution.width,
          height: activeResolution.height,
          fps: config.fps,
          totalFrames: framesCount,
          renderFrame: (ctx, _frameIdx, progress) => {
            renderLogoFrame(
              ctx,
              activeResolution.width,
              activeResolution.height,
              progress,
              config,
              customImage,
              null
            );
          },
          onProgress: (fraction, frameIdx) => {
            setExportProgress(Math.round(fraction * 100));
            setExportStatusText(`Mengompresi GIF frame ${frameIdx} / ${framesCount}...`);
          },
        });

        const url = URL.createObjectURL(gifBlob);
        const filename = `${(config.titleText || 'MemConstella')
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')}-animated-${activeResolution.width}x${
          activeResolution.height
        }.gif`;

        const newRecord: ExportRecord = {
          id: `gif-${Date.now()}`,
          format: 'GIF',
          url,
          filename,
          width: activeResolution.width,
          height: activeResolution.height,
          fps: config.fps,
          durationSec: config.loopDurationSec,
          sizeBytes: gifBlob.size,
          createdAt: new Date().toLocaleTimeString('id-ID', {
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
          }),
        };

        setExportsList((prev) => [newRecord, ...prev]);

        if (autoDownload) {
          const a = document.createElement('a');
          a.href = url;
          a.download = filename;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
        }
      } catch (err) {
        console.error('GIF encoding error:', err);
      } finally {
        setIsEncodingGif(false);
        setExportStatusText('');
      }
    },
    [
      isEncodingGif,
      isRecordingVideo,
      config,
      activeResolution.width,
      activeResolution.height,
      customImage,
    ]
  );

  // Trigger Video (.webm / .mp4) generation and download
  const handleExportVideo = async () => {
    if (isEncodingGif || isRecordingVideo) return;
    setIsRecordingVideo(true);
    setExportProgress(0);
    setExportStatusText('Merekam stream video resolusi tinggi...');

    try {
      if (document.fonts && document.fonts.ready) {
        await document.fonts.ready;
      }

      const framesCount = Math.round(config.fps * config.loopDurationSec);
      const { blob, extension } = await recordCanvasVideo({
        width: activeResolution.width,
        height: activeResolution.height,
        fps: config.fps,
        durationSec: config.loopDurationSec,
        renderFrame: (ctx, _frameIdx, progress) => {
          renderLogoFrame(
            ctx,
            activeResolution.width,
            activeResolution.height,
            progress,
            config,
            customImage,
            null
          );
        },
        onProgress: (fraction, frameIdx) => {
          setExportProgress(Math.round(fraction * 100));
          setExportStatusText(`Merekam Video frame ${frameIdx} / ${framesCount}...`);
        },
      });

      const url = URL.createObjectURL(blob);
      const filename = `${(config.titleText || 'MemConstella')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')}-motion-${activeResolution.width}x${
        activeResolution.height
      }.${extension}`;

      const newRecord: ExportRecord = {
        id: `vid-${Date.now()}`,
        format: 'WEBM',
        url,
        filename,
        width: activeResolution.width,
        height: activeResolution.height,
        fps: config.fps,
        durationSec: config.loopDurationSec,
        sizeBytes: blob.size,
        createdAt: new Date().toLocaleTimeString('id-ID', {
          hour: '2-digit',
          minute: '2-digit',
          second: '2-digit',
        }),
      };

      setExportsList((prev) => [newRecord, ...prev]);

      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    } catch (err) {
      console.error('Video export error:', err);
    } finally {
      setIsRecordingVideo(false);
      setExportStatusText('');
    }
  };

  // Interactive Canvas Star Dragging / Clicking
  const getNormalizedCoords = (
    e: React.MouseEvent<HTMLCanvasElement>
  ): { x: number; y: number } => {
    const canvas = canvasRef.current;
    if (!canvas) return { x: 0.5, y: 0.5 };
    const rect = canvas.getBoundingClientRect();
    const x = Math.max(0.02, Math.min(0.98, (e.clientX - rect.left) / rect.width));
    const y = Math.max(0.02, Math.min(0.98, (e.clientY - rect.top) / rect.height));
    return { x, y };
  };

  const handleCanvasMouseDown = (e: React.MouseEvent<HTMLCanvasElement>) => {
    if (!interactiveEditStars) return;
    const { x, y } = getNormalizedCoords(e);

    let closestId: string | null = null;
    let minDist = 0.045;
    for (const st of config.stars) {
      const dist = Math.hypot(st.x - x, st.y - y);
      if (dist < minDist) {
        minDist = dist;
        closestId = st.id;
      }
    }

    if (closestId) {
      setSelectedStarId(closestId);
      setDraggingStarId(closestId);
    }
  };

  const handleCanvasMouseMove = (e: React.MouseEvent<HTMLCanvasElement>) => {
    if (!interactiveEditStars || !draggingStarId) return;
    const { x, y } = getNormalizedCoords(e);
    setConfig((prev) => ({
      ...prev,
      stars: prev.stars.map((st) =>
        st.id === draggingStarId ? { ...st, x, y } : st
      ),
    }));
  };

  const handleCanvasMouseUp = () => {
    if (draggingStarId) {
      setDraggingStarId(null);
    }
  };

  // Custom image upload
  const handleCustomImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      const img = new Image();
      img.onload = () => {
        setCustomImage(img);
        setCustomImageName(file.name);
        updateConfig({ sourceMode: 'custom-image-hybrid' });
      };
      img.src = reader.result as string;
    };
    reader.readAsDataURL(file);
  };

  // Preset handlers
  const handleSelectGradientPreset = (presetId: string) => {
    const found = GRADIENT_PRESETS.find((p) => p.id === presetId);
    if (!found) return;
    updateConfig({
      gradientPresetId: found.id,
      gradientColors: [...found.colors] as [string, string, string, string],
      glowColor: found.glowColor,
      subtitleColor: found.subtitleColor,
      starTint: found.starTint,
    });
  };

  const handleSelectConstellationPreset = (presetId: string) => {
    const found = CONSTELLATION_PRESETS.find((c) => c.id === presetId);
    if (!found) return;
    updateConfig({
      constellationPresetId: found.id,
      stars: found.stars.map((s) => ({ ...s })),
      edges: found.edges.map((e) => ({ ...e })),
    });
    setSelectedStarId(found.stars[0]?.id || null);
  };

  const selectedStar = config.stars.find((s) => s.id === selectedStarId) || null;

  return (
    <div className="min-h-screen bg-[#0B0B1A] text-slate-100 flex flex-col font-sans">
      {/* =====================================================================
          TOP NAVIGATION BAR
         ===================================================================== */}
      <header className="flex items-center justify-between px-6 py-3.5 border-b border-slate-800/90 bg-[#0B0B1A]/95 sticky top-0 z-30">
        <div className="flex items-center gap-3">
          <a
            href="#studio"
            className="text-lg font-bold tracking-tight text-slate-100 whitespace-nowrap flex items-center gap-2"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            <Sparkles className="w-5 h-5 text-cyan-400" />
            <span>Logo Glow Animator</span>
          </a>
          <span className="text-xs px-2 py-0.5 rounded-full bg-cyan-950/70 border border-cyan-800 text-cyan-300 font-mono hidden sm:inline-block">
            HTML + GIF + Video
          </span>
        </div>

        {/* Navigation Tabs */}
        <nav className="hidden lg:flex items-center gap-6 text-sm font-medium text-slate-400">
          <button
            type="button"
            onClick={() => setActiveTab('html-code')}
            className={`hover:text-slate-100 transition-colors whitespace-nowrap py-1 border-b-2 flex items-center gap-1.5 cursor-pointer ${
              activeTab === 'html-code'
                ? 'text-cyan-300 border-cyan-400'
                : 'border-transparent'
            }`}
          >
            <Code2 className="w-4 h-4" />
            <span>Kode Animasi HTML</span>
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('gradient')}
            className={`hover:text-slate-100 transition-colors whitespace-nowrap py-1 border-b-2 cursor-pointer ${
              activeTab === 'gradient'
                ? 'text-cyan-300 border-cyan-400'
                : 'border-transparent'
            }`}
          >
            Gradasi Warna
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('stars')}
            className={`hover:text-slate-100 transition-colors whitespace-nowrap py-1 border-b-2 cursor-pointer ${
              activeTab === 'stars'
                ? 'text-cyan-300 border-cyan-400'
                : 'border-transparent'
            }`}
          >
            Bintang Kelap-Kelip
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('typography')}
            className={`hover:text-slate-100 transition-colors whitespace-nowrap py-1 border-b-2 cursor-pointer ${
              activeTab === 'typography'
                ? 'text-cyan-300 border-cyan-400'
                : 'border-transparent'
            }`}
          >
            Teks & Logo
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('exports')}
            className={`hover:text-slate-100 transition-colors whitespace-nowrap py-1 border-b-2 cursor-pointer ${
              activeTab === 'exports'
                ? 'text-cyan-300 border-cyan-400'
                : 'border-transparent'
            }`}
          >
            File Terunduh ({exportsList.length})
          </button>
        </nav>

        {/* Primary Download Actions */}
        <div className="flex items-center gap-2">
          {/* Direct HTML Code Download Button - Highlighted */}
          <button
            type="button"
            onClick={handleDownloadHtmlFile}
            className="px-3.5 py-2 text-xs font-bold text-slate-950 bg-gradient-to-r from-cyan-400 to-sky-400 hover:from-cyan-300 hover:to-sky-300 rounded-lg transition-all whitespace-nowrap flex items-center gap-1.5 cursor-pointer shadow-sm hover:shadow-cyan-400/20"
            title="Unduh file HTML mandiri yang siap diembed atau dibuka di browser"
          >
            <FileCode className="w-4 h-4 text-slate-950" />
            <span>Unduh HTML (.html)</span>
          </button>

          <button
            type="button"
            onClick={() => handleGenerateGif(true)}
            disabled={isEncodingGif || isRecordingVideo}
            className="px-3 py-2 text-xs font-semibold text-slate-100 bg-emerald-600 hover:bg-emerald-500 rounded-lg transition-colors whitespace-nowrap flex items-center gap-1.5 shadow-sm disabled:opacity-50 cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>{isEncodingGif ? 'GIF...' : 'Unduh GIF'}</span>
          </button>

          <button
            type="button"
            onClick={handleExportVideo}
            disabled={isEncodingGif || isRecordingVideo}
            className="px-3 py-2 text-xs font-semibold text-slate-200 bg-slate-800 border border-slate-700 rounded-lg hover:bg-slate-700 transition-colors whitespace-nowrap flex items-center gap-1.5 disabled:opacity-50 cursor-pointer"
          >
            <Film className="w-3.5 h-3.5 text-cyan-400" />
            <span className="hidden sm:inline">Unduh Video</span>
          </button>
        </div>
      </header>

      {/* =====================================================================
          MAIN WORKSPACE (Split Console: Settings & Code Left, Live Canvas Right)
         ===================================================================== */}
      <main
        id="studio"
        className="flex-1 max-w-[1520px] w-full mx-auto grid grid-cols-1 lg:grid-cols-12 gap-6 p-6"
      >
        {/* LEFT COLUMN: Controls & HTML Code Generator (5 cols) */}
        <aside className="lg:col-span-5 flex flex-col bg-[#0E131F] border border-slate-800 rounded-xl overflow-hidden shadow-xl">
          {/* Segmented Tab Bar */}
          <div className="p-2 bg-[#090D16] border-b border-slate-800 grid grid-cols-5 gap-1">
            <button
              type="button"
              onClick={() => setActiveTab('html-code')}
              className={`px-2 py-2 text-xs font-medium rounded-lg transition-colors whitespace-nowrap truncate flex items-center justify-center gap-1 cursor-pointer ${
                activeTab === 'html-code'
                  ? 'bg-slate-800 text-cyan-300 shadow-xs'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Code2 className="w-3.5 h-3.5 shrink-0" />
              <span>Kode HTML</span>
            </button>
            <button
              type="button"
              onClick={() => setActiveTab('gradient')}
              className={`px-2 py-2 text-xs font-medium rounded-lg transition-colors whitespace-nowrap truncate flex items-center justify-center gap-1 cursor-pointer ${
                activeTab === 'gradient'
                  ? 'bg-slate-800 text-cyan-300 shadow-xs'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Palette className="w-3.5 h-3.5 shrink-0" />
              <span>Gradasi</span>
            </button>
            <button
              type="button"
              onClick={() => setActiveTab('stars')}
              className={`px-2 py-2 text-xs font-medium rounded-lg transition-colors whitespace-nowrap truncate flex items-center justify-center gap-1 cursor-pointer ${
                activeTab === 'stars'
                  ? 'bg-slate-800 text-cyan-300 shadow-xs'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Sparkles className="w-3.5 h-3.5 shrink-0" />
              <span>Bintang</span>
            </button>
            <button
              type="button"
              onClick={() => setActiveTab('typography')}
              className={`px-2 py-2 text-xs font-medium rounded-lg transition-colors whitespace-nowrap truncate flex items-center justify-center gap-1 cursor-pointer ${
                activeTab === 'typography'
                  ? 'bg-slate-800 text-cyan-300 shadow-xs'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Sliders className="w-3.5 h-3.5 shrink-0" />
              <span>Logo</span>
            </button>
            <button
              type="button"
              onClick={() => setActiveTab('exports')}
              className={`px-2 py-2 text-xs font-medium rounded-lg transition-colors whitespace-nowrap truncate flex items-center justify-center gap-1 cursor-pointer ${
                activeTab === 'exports'
                  ? 'bg-slate-800 text-cyan-300 shadow-xs'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Download className="w-3.5 h-3.5 shrink-0" />
              <span>File ({exportsList.length})</span>
            </button>
          </div>

          {/* Active Tab Panel Content */}
          <div className="p-5 flex-1 overflow-y-auto space-y-6 max-h-[calc(100vh-210px)]">
            {/* =============================================================
                TAB: KODE ANIMASI HTML (HTML CODE GENERATOR)
               ============================================================= */}
            {activeTab === 'html-code' && (
              <div className="space-y-5">
                <div>
                  <div className="flex items-center justify-between mb-1">
                    <h2 className="text-sm font-semibold text-slate-100 flex items-center gap-1.5">
                      <Code2 className="w-4 h-4 text-cyan-400" />
                      <span>Kode HTML Dibalik Animasi Logo</span>
                    </h2>
                    <span className="text-[11px] font-mono text-cyan-400 bg-cyan-950/80 px-2 py-0.5 rounded border border-cyan-800">
                      Standalone .html
                    </span>
                  </div>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    Dapatkan kode HTML mandiri (bisa langsung diunduh, disalin, atau disematkan ke website, blog, aplikasi web, ataupun dokumen portofolio).
                  </p>
                </div>

                {/* Mode Selector: Pure SVG+CSS vs High-Perf Canvas+JS */}
                <div className="p-3 bg-[#090D16] rounded-xl border border-slate-800 space-y-3">
                  <span className="text-xs font-medium text-slate-300 block">
                    Pilih Format Arsitektur HTML:
                  </span>
                  <div className="grid grid-cols-2 gap-2">
                    <button
                      type="button"
                      onClick={() => setHtmlMode('svg-css')}
                      className={`p-2.5 rounded-lg border text-left transition-all cursor-pointer ${
                        htmlMode === 'svg-css'
                          ? 'bg-slate-800/90 border-cyan-400 text-slate-100'
                          : 'bg-[#0E131F] border-slate-800 text-slate-400 hover:text-slate-200'
                      }`}
                    >
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-xs font-semibold">Murni SVG + CSS</span>
                        {htmlMode === 'svg-css' && <Check className="w-3.5 h-3.5 text-cyan-400" />}
                      </div>
                      <p className="text-[11px] text-slate-400 line-clamp-2">
                        Tanpa dependensi JS, skalabel tajam, animasi via @keyframes CSS & filters.
                      </p>
                    </button>

                    <button
                      type="button"
                      onClick={() => setHtmlMode('canvas-js')}
                      className={`p-2.5 rounded-lg border text-left transition-all cursor-pointer ${
                        htmlMode === 'canvas-js'
                          ? 'bg-slate-800/90 border-cyan-400 text-slate-100'
                          : 'bg-[#0E131F] border-slate-800 text-slate-400 hover:text-slate-200'
                      }`}
                    >
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-xs font-semibold">HTML5 Canvas + JS</span>
                        {htmlMode === 'canvas-js' && <Check className="w-3.5 h-3.5 text-cyan-400" />}
                      </div>
                      <p className="text-[11px] text-slate-400 line-clamp-2">
                        Ultra 60fps dengan partikel cahaya halus, persis seperti rekaman video.
                      </p>
                    </button>
                  </div>
                </div>

                {/* Action Buttons for HTML */}
                <div className="flex flex-wrap items-center gap-2">
                  <button
                    type="button"
                    onClick={handleDownloadHtmlFile}
                    className="flex-1 px-4 py-2.5 text-xs font-semibold text-slate-950 bg-cyan-400 hover:bg-cyan-300 rounded-lg transition-colors flex items-center justify-center gap-2 cursor-pointer shadow-sm"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Unduh File .html</span>
                  </button>

                  <button
                    type="button"
                    onClick={handleCopyHtmlCode}
                    className="px-4 py-2.5 text-xs font-medium text-slate-200 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-lg transition-colors flex items-center justify-center gap-1.5 cursor-pointer"
                  >
                    {copySuccess ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-400" />
                        <span className="text-emerald-400 font-semibold">Tersalin!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5 text-slate-300" />
                        <span>Salin Kode</span>
                      </>
                    )}
                  </button>

                  <button
                    type="button"
                    onClick={() => setShowLiveHtmlPreview((prev) => !prev)}
                    className={`px-3 py-2.5 text-xs font-medium rounded-lg border transition-colors flex items-center gap-1.5 cursor-pointer ${
                      showLiveHtmlPreview
                        ? 'bg-cyan-950/80 border-cyan-500 text-cyan-300'
                        : 'bg-slate-800 border-slate-700 text-slate-300 hover:bg-slate-700'
                    }`}
                    title="Uji coba render HTML ini langsung di iframe"
                  >
                    <Eye className="w-3.5 h-3.5" />
                    <span>{showLiveHtmlPreview ? 'Sembunyikan Sandbox' : 'Uji Sandbox'}</span>
                  </button>
                </div>

                {/* Optional Live Sandbox iframe */}
                {showLiveHtmlPreview && (
                  <div className="p-3 bg-[#0B0B1A] border border-cyan-500/40 rounded-xl space-y-2">
                    <div className="flex items-center justify-between text-xs text-cyan-300 font-medium">
                      <span>Pratinjau Langsung dari Output Kode HTML di atas:</span>
                      <span className="text-[10px] text-slate-400">Sandbox Iframe Terisolasi</span>
                    </div>
                    <div className="w-full h-44 rounded-lg overflow-hidden border border-slate-800 bg-[#0B0B1A]">
                      <iframe
                        title="Live HTML Code Preview"
                        srcDoc={generatedHtmlCode}
                        className="w-full h-full border-0 pointer-events-none"
                        sandbox="allow-scripts allow-same-origin"
                      />
                    </div>
                  </div>
                )}

                {/* Code Preview Block */}
                <div className="space-y-2">
                  <div className="flex items-center justify-between text-xs text-slate-400">
                    <span className="font-mono">
                      {htmlMode === 'svg-css' ? 'index-svg-css.html' : 'index-canvas.html'} (
                      {(generatedHtmlCode.length / 1024).toFixed(1)} KB)
                    </span>
                    <span className="text-[11px] text-slate-500">
                      Otomatis tersinkron dengan perubahan slider
                    </span>
                  </div>
                  <div className="relative group">
                    <pre className="p-3.5 rounded-xl bg-[#070A10] border border-slate-800 text-slate-300 font-mono text-[11px] leading-relaxed overflow-x-auto max-h-[300px] select-all">
                      <code>{generatedHtmlCode}</code>
                    </pre>
                    <button
                      type="button"
                      onClick={handleCopyHtmlCode}
                      className="absolute top-2 right-2 px-2.5 py-1 rounded bg-slate-800/90 border border-slate-700 text-[11px] text-slate-200 hover:bg-slate-700 transition-colors flex items-center gap-1 cursor-pointer"
                    >
                      <Copy className="w-3 h-3" />
                      <span>{copySuccess ? 'Tersalin' : 'Salin'}</span>
                    </button>
                  </div>
                </div>

                {/* How to use documentation banner */}
                <div className="p-3 rounded-lg bg-slate-900/60 border border-slate-800/80 text-xs text-slate-400 space-y-1">
                  <span className="font-semibold text-slate-200 block">
                    Cara Menggunakan Kode HTML:
                  </span>
                  <p>
                    1. Klik tombol <strong>Unduh File .html</strong> lalu buka langsung di browser Chrome / Firefox / Safari.
                  </p>
                  <p>
                    2. Atau klik <strong>Salin Kode</strong> dan tempel ke file HTML project Anda, WordPress, Webflow, atau elemen iframe.
                  </p>
                </div>
              </div>
            )}

            {/* =============================================================
                TAB: GRADASI WARNA (COLOR GRADIENT CONTROLS)
               ============================================================= */}
            {activeTab === 'gradient' && (
              <div className="space-y-6">
                <div>
                  <h2 className="text-sm font-semibold text-slate-100 mb-1">
                    Tema Gradasi Warna Bergerak
                  </h2>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    Pilih skema warna mengalir untuk teks utama MemConstella dan pendaran cahaya nebula.
                  </p>
                </div>

                {/* Preset List */}
                <div className="space-y-2">
                  {GRADIENT_PRESETS.map((preset) => {
                    const isSelected = config.gradientPresetId === preset.id;
                    return (
                      <button
                        key={preset.id}
                        type="button"
                        onClick={() => handleSelectGradientPreset(preset.id)}
                        className={`w-full text-left p-3 rounded-lg border transition-all cursor-pointer ${
                          isSelected
                            ? 'bg-slate-800/90 border-cyan-500/60'
                            : 'bg-[#090D16]/70 border-slate-800/80 hover:border-slate-700'
                        }`}
                      >
                        <div className="flex items-center justify-between mb-1.5">
                          <span className="text-xs font-semibold text-slate-100">
                            {preset.name}
                          </span>
                          <div className="flex items-center gap-1">
                            {preset.colors.map((hex, i) => (
                              <span
                                key={i}
                                className="w-3.5 h-3.5 rounded-full border border-white/20"
                                style={{ backgroundColor: hex }}
                              />
                            ))}
                          </div>
                        </div>
                        <p className="text-xs text-slate-400 line-clamp-1">
                          {preset.description}
                        </p>
                      </button>
                    );
                  })}
                </div>

                {/* 4 Custom Color Pickers */}
                <div className="pt-4 border-t border-slate-800/80">
                  <div className="flex items-center justify-between mb-2.5">
                    <span className="text-xs font-medium text-slate-300">
                      Kustomisasi 4 Titik Gradasi
                    </span>
                    <span className="text-xs font-mono text-slate-400 tabular-nums">
                      {config.gradientColors.join(' · ')}
                    </span>
                  </div>
                  <div className="grid grid-cols-4 gap-2.5">
                    {config.gradientColors.map((hex, idx) => (
                      <label
                        key={idx}
                        className="flex flex-col items-center gap-1.5 p-2 rounded-lg bg-[#090D16] border border-slate-800 cursor-pointer hover:border-slate-700"
                      >
                        <input
                          type="color"
                          value={hex}
                          onChange={(e) => {
                            const next = [...config.gradientColors] as [
                              string,
                              string,
                              string,
                              string,
                            ];
                            next[idx] = e.target.value;
                            updateConfig({
                              gradientPresetId: 'custom',
                              gradientColors: next,
                            });
                          }}
                          className="w-7 h-7 rounded cursor-pointer bg-transparent border-0"
                        />
                        <span className="text-[11px] font-mono text-slate-400 uppercase tabular-nums">
                          {hex}
                        </span>
                      </label>
                    ))}
                  </div>
                </div>

                {/* Gradient Wave Style */}
                <div className="pt-4 border-t border-slate-800/80 space-y-3">
                  <label className="block text-xs font-medium text-slate-300">
                    Mode Gelombang Gradasi
                  </label>
                  <div className="grid grid-cols-2 gap-1.5 p-1 bg-[#090D16] rounded-lg border border-slate-800/80">
                    {(
                      [
                        { id: 'linear-flow', label: 'Linear Mengalir' },
                        { id: 'bi-aurora', label: 'Aurora Berkilau' },
                        { id: 'radial-pulse', label: 'Denyut Radial' },
                        { id: 'prism-shimmer', label: 'Gelombang Prisma' },
                      ] as { id: GradientWaveMode; label: string }[]
                    ).map((m) => (
                      <button
                        key={m.id}
                        type="button"
                        onClick={() => updateConfig({ gradientMode: m.id })}
                        className={`px-2.5 py-1.5 text-xs font-medium rounded-md transition-colors whitespace-nowrap cursor-pointer ${
                          config.gradientMode === m.id
                            ? 'bg-slate-800 text-cyan-300'
                            : 'text-slate-400 hover:text-slate-200'
                        }`}
                      >
                        {m.label}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Sliders for Gradient Flow */}
                <div className="pt-4 border-t border-slate-800/80 space-y-4">
                  <div>
                    <div className="flex justify-between text-xs mb-1.5">
                      <span className="text-slate-300">Kecepatan Aliran Gradasi</span>
                      <span className="font-mono text-cyan-300 tabular-nums">
                        {config.gradientCycles}x Siklus / Loop
                      </span>
                    </div>
                    <input
                      type="range"
                      min={1}
                      max={3}
                      step={1}
                      value={config.gradientCycles}
                      onChange={(e) =>
                        updateConfig({ gradientCycles: Number(e.target.value) })
                      }
                      className="w-full"
                    />
                  </div>

                  <div>
                    <div className="flex justify-between text-xs mb-1.5">
                      <span className="text-slate-300">Intensitas Cahaya (Neon Glow)</span>
                      <span className="font-mono text-cyan-300 tabular-nums">
                        {Math.round(config.textGlowIntensity * 100)} %
                      </span>
                    </div>
                    <input
                      type="range"
                      min={0}
                      max={1}
                      step={0.05}
                      value={config.textGlowIntensity}
                      onChange={(e) =>
                        updateConfig({ textGlowIntensity: Number(e.target.value) })
                      }
                      className="w-full"
                    />
                  </div>

                  <div>
                    <div className="flex justify-between text-xs mb-1.5">
                      <span className="text-slate-300">Sudut Kemiringan Gradasi</span>
                      <span className="font-mono text-cyan-300 tabular-nums">
                        {config.gradientAngle}°
                      </span>
                    </div>
                    <input
                      type="range"
                      min={0}
                      max={90}
                      step={2}
                      value={config.gradientAngle}
                      onChange={(e) =>
                        updateConfig({ gradientAngle: Number(e.target.value) })
                      }
                      className="w-full"
                    />
                  </div>

                  <label className="flex items-center justify-between pt-2 cursor-pointer">
                    <span className="text-xs text-slate-300">
                      Kilau Cahaya Menyapu Huruf (Shimmer Sweep)
                    </span>
                    <input
                      type="checkbox"
                      checked={config.shimmerSweep}
                      onChange={(e) =>
                        updateConfig({ shimmerSweep: e.target.checked })
                      }
                      className="w-4 h-4 accent-cyan-400 rounded cursor-pointer"
                    />
                  </label>
                </div>
              </div>
            )}

            {/* =============================================================
                TAB: BINTANG KELAP-KELIP & KONSTELASI
               ============================================================= */}
            {activeTab === 'stars' && (
              <div className="space-y-6">
                <div>
                  <h2 className="text-sm font-semibold text-slate-100 mb-1">
                    Konstelasi & Bintang Berkelap-Kelip
                  </h2>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    Atur kerlipan bintang rasi Ursa Major (Big Dipper) di atas logo serta taburan bintang angkasa.
                  </p>
                </div>

                {/* Constellation Presets */}
                <div className="space-y-2">
                  <span className="block text-xs font-medium text-slate-300">
                    Pola Rasi Bintang
                  </span>
                  {CONSTELLATION_PRESETS.map((cp) => {
                    const isSelected = config.constellationPresetId === cp.id;
                    return (
                      <button
                        key={cp.id}
                        type="button"
                        onClick={() => handleSelectConstellationPreset(cp.id)}
                        className={`w-full text-left p-3 rounded-lg border transition-all cursor-pointer ${
                          isSelected
                            ? 'bg-slate-800/90 border-cyan-500/60'
                            : 'bg-[#090D16]/70 border-slate-800/80 hover:border-slate-700'
                        }`}
                      >
                        <div className="flex items-center justify-between">
                          <span className="text-xs font-semibold text-slate-100">
                            {cp.name}
                          </span>
                          <span className="text-xs font-mono text-cyan-400 tabular-nums">
                            {cp.stars.length} Bintang
                          </span>
                        </div>
                        <p className="text-xs text-slate-400 mt-0.5">
                          {cp.scientificName}
                        </p>
                      </button>
                    );
                  })}
                </div>

                {/* Twinkle & Flare Sliders */}
                <div className="pt-4 border-t border-slate-800/80 space-y-4">
                  <div>
                    <div className="flex justify-between text-xs mb-1.5">
                      <span className="text-slate-300">Intensitas Kerlip Bintang</span>
                      <span className="font-mono text-cyan-300 tabular-nums">
                        {Math.round(config.twinkleIntensity * 100)} %
                      </span>
                    </div>
                    <input
                      type="range"
                      min={0.1}
                      max={1.0}
                      step={0.05}
                      value={config.twinkleIntensity}
                      onChange={(e) =>
                        updateConfig({ twinkleIntensity: Number(e.target.value) })
                      }
                      className="w-full"
                    />
                  </div>

                  <div>
                    <div className="flex justify-between text-xs mb-1.5">
                      <span className="text-slate-300">Frekuensi Kelap-Kelip</span>
                      <span className="font-mono text-cyan-300 tabular-nums">
                        {config.twinkleSpeedMultiplier}x Harmonik
                      </span>
                    </div>
                    <input
                      type="range"
                      min={1}
                      max={3}
                      step={1}
                      value={config.twinkleSpeedMultiplier}
                      onChange={(e) =>
                        updateConfig({
                          twinkleSpeedMultiplier: Number(e.target.value),
                        })
                      }
                      className="w-full"
                    />
                  </div>

                  <div>
                    <div className="flex justify-between text-xs mb-1.5">
                      <span className="text-slate-300">Panjang Sinar Bintang (4-Point Flare)</span>
                      <span className="font-mono text-cyan-300 tabular-nums">
                        {(config.spikeLength * 100).toFixed(0)} %
                      </span>
                    </div>
                    <input
                      type="range"
                      min={0.4}
                      max={2.2}
                      step={0.1}
                      value={config.spikeLength}
                      onChange={(e) =>
                        updateConfig({ spikeLength: Number(e.target.value) })
                      }
                      className="w-full"
                    />
                  </div>

                  <div>
                    <div className="flex justify-between text-xs mb-1.5">
                      <span className="text-slate-300">Kecerahan Garis Rasi</span>
                      <span className="font-mono text-cyan-300 tabular-nums">
                        {Math.round(config.lineOpacity * 100)} %
                      </span>
                    </div>
                    <input
                      type="range"
                      min={0}
                      max={1}
                      step={0.05}
                      value={config.lineOpacity}
                      onChange={(e) =>
                        updateConfig({ lineOpacity: Number(e.target.value) })
                      }
                      className="w-full"
                    />
                  </div>

                  <div>
                    <div className="flex justify-between text-xs mb-1.5">
                      <span className="text-slate-300">Jumlah Bintang Latar Belakang</span>
                      <span className="font-mono text-cyan-300 tabular-nums">
                        {config.ambientStarCount} Titik
                      </span>
                    </div>
                    <input
                      type="range"
                      min={0}
                      max={75}
                      step={5}
                      value={config.ambientStarCount}
                      onChange={(e) =>
                        updateConfig({ ambientStarCount: Number(e.target.value) })
                      }
                      className="w-full"
                    />
                  </div>

                  <div className="space-y-2.5 pt-1">
                    <label className="flex items-center justify-between cursor-pointer">
                      <span className="text-xs text-slate-300">
                        Aliran Cahaya Energi pada Garis Rasi
                      </span>
                      <input
                        type="checkbox"
                        checked={config.linePulse}
                        onChange={(e) =>
                          updateConfig({ linePulse: e.target.checked })
                        }
                        className="w-4 h-4 accent-cyan-400 rounded cursor-pointer"
                      />
                    </label>

                    <label className="flex items-center justify-between cursor-pointer">
                      <span className="text-xs text-slate-300">
                        Bintang Jatuh (Shooting Star) Periodik
                      </span>
                      <input
                        type="checkbox"
                        checked={config.shootingStars}
                        onChange={(e) =>
                          updateConfig({ shootingStars: e.target.checked })
                        }
                        className="w-4 h-4 accent-cyan-400 rounded cursor-pointer"
                      />
                    </label>
                  </div>
                </div>
              </div>
            )}

            {/* =============================================================
                TAB: TEKS LOGO & PENGATURAN KANVAS
               ============================================================= */}
            {activeTab === 'typography' && (
              <div className="space-y-6">
                <div>
                  <h2 className="text-sm font-semibold text-slate-100 mb-1">
                    Teks Logo & Sumber Gambar
                  </h2>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    Kustomisasi teks judul MemConstella, subjudul, dan opsi unggah logo sendiri.
                  </p>
                </div>

                <div className="space-y-3">
                  <div>
                    <label className="block text-xs font-medium text-slate-300 mb-1">
                      Teks Judul Logo
                    </label>
                    <input
                      type="text"
                      value={config.titleText}
                      onChange={(e) => updateConfig({ titleText: e.target.value })}
                      className="w-full px-3 py-2 text-sm bg-[#090D16] border border-slate-800 rounded-lg text-slate-100 focus:outline-none focus:border-cyan-400"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-medium text-slate-300 mb-1">
                      Teks Subjudul (Tagline)
                    </label>
                    <input
                      type="text"
                      value={config.subtitleText}
                      onChange={(e) => updateConfig({ subtitleText: e.target.value })}
                      className="w-full px-3 py-2 text-sm bg-[#090D16] border border-slate-800 rounded-lg text-slate-100 focus:outline-none focus:border-cyan-400"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-medium text-slate-300 mb-1">
                      Pilihan Font
                    </label>
                    <select
                      value={config.fontFamily}
                      onChange={(e) =>
                        updateConfig({
                          fontFamily: e.target.value as any,
                        })
                      }
                      className="w-full px-3 py-2 text-sm bg-[#090D16] border border-slate-800 rounded-lg text-slate-100 focus:outline-none focus:border-cyan-400"
                    >
                      <option value="Plus Jakarta Sans">Plus Jakarta Sans (Modern Geometric)</option>
                      <option value="Outfit">Outfit (Clean Astro)</option>
                      <option value="Syne">Syne (Bold Display)</option>
                    </select>
                  </div>
                </div>

                {/* Upload Image Option */}
                <div className="pt-4 border-t border-slate-800/80 space-y-2">
                  <span className="block text-xs font-medium text-slate-300">
                    Atau Gunakan Logo Gambar Sendiri:
                  </span>
                  <div className="flex items-center gap-2">
                    <button
                      type="button"
                      onClick={() => fileInputRef.current?.click()}
                      className="px-3 py-2 text-xs font-medium bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg border border-slate-700 flex items-center gap-1.5 cursor-pointer"
                    >
                      <Upload className="w-3.5 h-3.5 text-cyan-400" />
                      <span>Unggah Gambar Logo</span>
                    </button>
                    {customImage && (
                      <span className="text-xs text-slate-400 truncate">
                        {customImageName}
                      </span>
                    )}
                  </div>
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept="image/*"
                    onChange={handleCustomImageUpload}
                    className="hidden"
                  />
                </div>
              </div>
            )}

            {/* =============================================================
                TAB: HASIL EKSPOR & UNDUHAN (FILES LIST)
               ============================================================= */}
            {activeTab === 'exports' && (
              <div className="space-y-4">
                <div>
                  <h2 className="text-sm font-semibold text-slate-100 mb-1">
                    Daftar File Animasi yang Dihasilkan
                  </h2>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    Semua berkas HTML, GIF, dan Video yang telah diunduh selama sesi ini.
                  </p>
                </div>

                {exportsList.length === 0 ? (
                  <div className="p-8 text-center rounded-xl bg-[#090D16] border border-dashed border-slate-800 text-slate-500 space-y-2">
                    <FileCode className="w-8 h-8 mx-auto text-slate-600" />
                    <p className="text-xs">Belum ada file yang diekspor.</p>
                    <p className="text-[11px] text-slate-600">
                      Gunakan tombol "Unduh Kode HTML", "Unduh GIF", atau "Unduh Video" di atas.
                    </p>
                  </div>
                ) : (
                  <div className="space-y-2">
                    {exportsList.map((rec) => (
                      <div
                        key={rec.id}
                        className="p-3 rounded-lg bg-[#090D16] border border-slate-800 flex items-center justify-between"
                      >
                        <div className="min-w-0 pr-3">
                          <div className="flex items-center gap-2">
                            <span
                              className={`text-[10px] font-mono px-1.5 py-0.5 rounded font-bold ${
                                rec.format === 'HTML'
                                  ? 'bg-amber-950 text-amber-300 border border-amber-800'
                                  : rec.format === 'GIF'
                                  ? 'bg-emerald-950 text-emerald-300 border border-emerald-800'
                                  : 'bg-cyan-950 text-cyan-300 border border-cyan-800'
                              }`}
                            >
                              {rec.format}
                            </span>
                            <span className="text-xs font-medium text-slate-200 truncate">
                              {rec.filename}
                            </span>
                          </div>
                          <span className="text-[11px] text-slate-500 font-mono mt-0.5 block">
                            {formatBytes(rec.sizeBytes)} · {rec.createdAt}
                          </span>
                        </div>
                        <a
                          href={rec.url}
                          download={rec.filename}
                          className="px-2.5 py-1.5 text-xs bg-slate-800 hover:bg-slate-700 text-cyan-300 rounded border border-slate-700 flex items-center gap-1 cursor-pointer shrink-0"
                        >
                          <Download className="w-3 h-3" />
                          <span>Unduh</span>
                        </a>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        </aside>

        {/* RIGHT COLUMN: Interactive Live Canvas & Preview Zone (7 cols) */}
        <section className="lg:col-span-7 flex flex-col space-y-4">
          {/* Main Visual Display Card */}
          <div className="bg-[#0E131F] border border-slate-800 rounded-xl p-4 flex flex-col space-y-3 shadow-xl">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse" />
                <span className="text-xs font-semibold text-slate-200">
                  Pratinjau Animasi Real-Time (60 FPS)
                </span>
              </div>

              {/* Resolution indicator */}
              <div className="flex items-center gap-2 text-xs font-mono text-slate-400">
                <span>
                  {activeResolution.width} × {activeResolution.height}
                </span>
                <span>•</span>
                <span className="text-cyan-400">
                  Frame {currentFrameNumber} / {totalFrames}
                </span>
              </div>
            </div>

            {/* Canvas Viewport */}
            <div className="relative w-full aspect-[5/2] bg-[#0B0B1A] rounded-lg overflow-hidden border border-slate-800/90 shadow-2xl flex items-center justify-center">
              <canvas
                ref={canvasRef}
                width={activeResolution.width}
                height={activeResolution.height}
                onMouseDown={handleCanvasMouseDown}
                onMouseMove={handleCanvasMouseMove}
                onMouseUp={handleCanvasMouseUp}
                className={`w-full h-full object-contain ${
                  interactiveEditStars ? 'cursor-crosshair' : 'cursor-default'
                }`}
              />

              {/* Progress bar overlay along bottom */}
              <div className="absolute bottom-0 left-0 right-0 h-1 bg-slate-900/60">
                <div
                  className="h-full bg-cyan-400 transition-all duration-75"
                  style={{ width: `${(loopProgress * 100).toFixed(1)}%` }}
                />
              </div>

              {/* Encoding / Recording Progress Overlay */}
              {(isEncodingGif || isRecordingVideo) && (
                <div className="absolute inset-0 bg-[#0B0B1A]/90 backdrop-blur-xs flex flex-col items-center justify-center p-6 text-center space-y-3 z-20">
                  <div className="w-10 h-10 border-3 border-cyan-400 border-t-transparent rounded-full animate-spin" />
                  <div>
                    <h3 className="text-sm font-semibold text-slate-100">
                      {isEncodingGif ? 'Sedang Membuat Animasi GIF...' : 'Sedang Merekam Video...'}
                    </h3>
                    <p className="text-xs text-slate-400 mt-1">{exportStatusText}</p>
                  </div>
                  <div className="w-64 bg-slate-800 h-2 rounded-full overflow-hidden">
                    <div
                      className="bg-cyan-400 h-full transition-all duration-150"
                      style={{ width: `${exportProgress}%` }}
                    />
                  </div>
                </div>
              )}
            </div>

            {/* Playback & Interaction Controls */}
            <div className="flex flex-wrap items-center justify-between gap-3 pt-1">
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => setIsPlaying((p) => !p)}
                  className="px-3 py-1.5 text-xs font-medium rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 flex items-center gap-1.5 cursor-pointer"
                >
                  {isPlaying ? (
                    <>
                      <Pause className="w-3.5 h-3.5 text-amber-400" />
                      <span>Jeda</span>
                    </>
                  ) : (
                    <>
                      <Play className="w-3.5 h-3.5 text-emerald-400" />
                      <span>Putar</span>
                    </>
                  )}
                </button>

                <button
                  type="button"
                  onClick={() => {
                    progressRef.current = 0;
                    setLoopProgress(0);
                  }}
                  className="px-3 py-1.5 text-xs font-medium rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 flex items-center gap-1.5 cursor-pointer"
                >
                  <RotateCcw className="w-3.5 h-3.5" />
                  <span>Ulangi Loop</span>
                </button>
              </div>

              {/* Quick Jump to HTML Code Tab */}
              <button
                type="button"
                onClick={() => setActiveTab('html-code')}
                className="px-3 py-1.5 text-xs font-medium rounded-lg bg-cyan-950/70 border border-cyan-700/60 text-cyan-300 hover:bg-cyan-900/60 flex items-center gap-1.5 cursor-pointer"
              >
                <Code2 className="w-3.5 h-3.5" />
                <span>Lihat Kode HTML Lengkap</span>
              </button>
            </div>
          </div>

          {/* DEDICATED PROMINENT DOWNLOAD HUB CARD */}
          <div className="bg-[#0E131F] border border-cyan-500/40 rounded-xl p-5 space-y-3.5 shadow-2xl">
            <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2">
                <Download className="w-4 h-4 text-cyan-400" />
                <h3 className="text-sm font-bold text-slate-100">
                  Unduh Berkas Animasi Logo Ini:
                </h3>
              </div>
              <span className="text-[11px] font-mono text-cyan-300 bg-cyan-950/90 px-2.5 py-0.5 rounded-full border border-cyan-800">
                Pilih Format: .HTML · .GIF · .WEBM
              </span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {/* BUTTON 1: UNDUH FILE HTML (.HTML) - BIG & PROMINENT */}
              <button
                type="button"
                onClick={handleDownloadHtmlFile}
                className="p-3.5 rounded-xl bg-gradient-to-br from-cyan-400 to-sky-500 hover:from-cyan-300 hover:to-sky-400 text-slate-950 font-bold text-xs flex flex-col items-center justify-center gap-1.5 shadow-lg shadow-cyan-500/20 hover:scale-[1.02] transition-all cursor-pointer group text-center"
              >
                <div className="flex items-center gap-2 text-sm font-extrabold text-slate-950">
                  <FileCode className="w-5 h-5" />
                  <span>Unduh File HTML (.html)</span>
                </div>
                <span className="text-[11px] text-slate-900 font-medium">
                  {htmlMode === 'svg-css' ? 'Format SVG + CSS (Tanpa JS)' : 'Format Canvas JS (60 FPS)'}
                </span>
                <span className="text-[10px] bg-slate-950/20 px-2 py-0.5 rounded-full text-slate-950 font-semibold">
                  Klik untuk langsung unduh
                </span>
              </button>

              {/* BUTTON 2: UNDUH ANIMASI GIF */}
              <button
                type="button"
                onClick={() => handleGenerateGif(true)}
                disabled={isEncodingGif || isRecordingVideo}
                className="p-3.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs flex flex-col items-center justify-center gap-1.5 shadow-lg shadow-emerald-500/20 hover:scale-[1.02] transition-all cursor-pointer disabled:opacity-50 text-center"
              >
                <div className="flex items-center gap-2 text-sm font-extrabold text-slate-950">
                  <Download className="w-5 h-5" />
                  <span>Unduh Animasi GIF (.gif)</span>
                </div>
                <span className="text-[11px] text-slate-900 font-medium">
                  {isEncodingGif ? 'Sedang memproses frame...' : 'Loop gambar bergerak mulus'}
                </span>
                <span className="text-[10px] bg-slate-950/20 px-2 py-0.5 rounded-full text-slate-950 font-semibold">
                  Cocok untuk logo banner
                </span>
              </button>

              {/* BUTTON 3: UNDUH VIDEO */}
              <button
                type="button"
                onClick={handleExportVideo}
                disabled={isEncodingGif || isRecordingVideo}
                className="p-3.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-100 font-bold text-xs border border-slate-700 flex flex-col items-center justify-center gap-1.5 shadow-md hover:scale-[1.02] transition-all cursor-pointer disabled:opacity-50 text-center"
              >
                <div className="flex items-center gap-2 text-sm font-extrabold text-cyan-300">
                  <Film className="w-5 h-5 text-cyan-400" />
                  <span>Unduh Video (.webm)</span>
                </div>
                <span className="text-[11px] text-slate-400 font-medium">
                  {isRecordingVideo ? 'Sedang merekam video...' : 'Video resolusi tinggi 60 FPS'}
                </span>
                <span className="text-[10px] bg-slate-900/60 px-2 py-0.5 rounded-full text-slate-400">
                  Kualitas bitrate tinggi
                </span>
              </button>
            </div>

            {/* Quick HTML options bar */}
            <div className="flex flex-wrap items-center justify-between gap-3 pt-2 text-xs border-t border-slate-800/80">
              <div className="flex items-center gap-2 text-slate-400">
                <span>Mode HTML:</span>
                <button
                  type="button"
                  onClick={() => setHtmlMode('svg-css')}
                  className={`px-2 py-0.5 rounded text-[11px] font-medium transition-colors cursor-pointer ${
                    htmlMode === 'svg-css'
                      ? 'bg-cyan-950 text-cyan-300 border border-cyan-700'
                      : 'bg-slate-800 text-slate-400 hover:text-slate-200'
                  }`}
                >
                  SVG + CSS (Standar)
                </button>
                <button
                  type="button"
                  onClick={() => setHtmlMode('canvas-js')}
                  className={`px-2 py-0.5 rounded text-[11px] font-medium transition-colors cursor-pointer ${
                    htmlMode === 'canvas-js'
                      ? 'bg-cyan-950 text-cyan-300 border border-cyan-700'
                      : 'bg-slate-800 text-slate-400 hover:text-slate-200'
                  }`}
                >
                  Canvas + JS
                </button>
              </div>

              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleCopyHtmlCode}
                  className="px-3 py-1.5 text-xs text-slate-200 bg-slate-800 hover:bg-slate-700 rounded-lg border border-slate-700 flex items-center gap-1.5 cursor-pointer"
                >
                  {copySuccess ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-emerald-400" />
                      <span className="text-emerald-400 font-semibold">Tersalin!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5 text-slate-400" />
                      <span>Salin Kode HTML</span>
                    </>
                  )}
                </button>

                <button
                  type="button"
                  onClick={() => setActiveTab('html-code')}
                  className="px-3 py-1.5 text-xs text-cyan-300 bg-cyan-950/60 hover:bg-cyan-900/60 rounded-lg border border-cyan-800 flex items-center gap-1.5 cursor-pointer"
                >
                  <Code2 className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Lihat Kode HTML</span>
                </button>
              </div>
            </div>
          </div>

          {/* Quick Features Highlight Banner */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="p-3.5 rounded-xl bg-[#0E131F] border border-slate-800 space-y-1">
              <div className="flex items-center gap-2 text-cyan-400 text-xs font-semibold">
                <FileCode className="w-4 h-4" />
                <span>Kode HTML Mandiri</span>
              </div>
              <p className="text-[11px] text-slate-400 leading-relaxed">
                Tersedia versi <strong>SVG + CSS</strong> tanpa JS ataupun <strong>Canvas 60fps</strong> yang dapat langsung diunduh berupa file <code>.html</code>.
              </p>
            </div>

            <div className="p-3.5 rounded-xl bg-[#0E131F] border border-slate-800 space-y-1">
              <div className="flex items-center gap-2 text-cyan-400 text-xs font-semibold">
                <Palette className="w-4 h-4" />
                <span>Gradasi Bergerak Mulus</span>
              </div>
              <p className="text-[11px] text-slate-400 leading-relaxed">
                Gradasi 4 warna dinamis yang mengalir melintasi tipografi logo dengan pendaran neon glow.
              </p>
            </div>

            <div className="p-3.5 rounded-xl bg-[#0E131F] border border-slate-800 space-y-1">
              <div className="flex items-center gap-2 text-cyan-400 text-xs font-semibold">
                <Sparkles className="w-4 h-4" />
                <span>Bintang Berkelap-Kelip</span>
              </div>
              <p className="text-[11px] text-slate-400 leading-relaxed">
                Rasi Ursa Major (Big Dipper) dengan pendaran flare 4-penjuru dan pulsa energi pada garis rasi.
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
